/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.*;
import seguridad.ControlRegistro;
import seguridad.Sesion;
import seguridad.Usuario;
import seguridad.ValidarAcceso;

/**
 *
 * @author MISAEL JIMENEZ
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnIniciarS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        lblFondoI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Bienvenid@ al Sistema SIBAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 25, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\nGestiona fácilmente el inventario, registra movimientos de entrada y salida.\n    Controla proveedores y administra usuarios, todo desde un solo lugar.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 70, 425, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnIniciarS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciarS.setText("INICIA SESION");
        btnIniciarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("O");

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setText("REGISTRATE");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIniciarS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnIniciarS)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 174, -1, -1));
        getContentPane().add(lblFondoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
         // Crear panel personalizado para registro
    JPanel panel = new JPanel(new GridLayout(5, 2, 10, 10));
    
    JTextField txtNombre = new JTextField(15);
    JTextField txtUsuario = new JTextField(15);
    JPasswordField txtPassword = new JPasswordField(15);
    JPasswordField txtConfirmPassword = new JPasswordField(15);
    
    // ComboBox para el rol
    String[] roles = {"Encargado", "Administrador"};
    JComboBox<String> cmbRol = new JComboBox<>(roles);
    
    panel.add(new JLabel("Nombre completo:"));
    panel.add(txtNombre);
    panel.add(new JLabel("Usuario:"));
    panel.add(txtUsuario);
    panel.add(new JLabel("Contraseña:"));
    panel.add(txtPassword);
    panel.add(new JLabel("Confirmar contraseña:"));
    panel.add(txtConfirmPassword);
    panel.add(new JLabel("Rol:"));
    panel.add(cmbRol);
    
    int resultado = JOptionPane.showConfirmDialog(
        this, 
        panel, 
        "Crear Cuenta - SIBAL", 
        JOptionPane.OK_CANCEL_OPTION, 
        JOptionPane.PLAIN_MESSAGE
    );
    
    if (resultado == JOptionPane.OK_OPTION) {
        String nombre = txtNombre.getText().trim();
        String usuario = txtUsuario.getText().trim();
        String password = new String(txtPassword.getPassword());
        String confirmPassword = new String(txtConfirmPassword.getPassword());
        String rol = (String) cmbRol.getSelectedItem();
        
        // Validaciones
        if (nombre.isEmpty() || usuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(
                this, 
                "Todos los campos son obligatorios", 
                "Campos vacíos", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        if (password.length() < 4) {
            JOptionPane.showMessageDialog(
                this, 
                "La contraseña debe tener al menos 4 caracteres", 
                "Contraseña débil", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(
                this, 
                "Las contraseñas no coinciden", 
                "Error", 
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        // Crear objeto Usuario
        Usuario nuevoUsuario = new Usuario(nombre, usuario, password, rol);
        
        // Registrar en BD
        ControlRegistro controlRegistro = new ControlRegistro();
        boolean registrado = controlRegistro.registrarUsuario(nuevoUsuario);
        
        if (registrado) {
            JOptionPane.showMessageDialog(
                this, 
                "¡Cuenta creada exitosamente!\n" +
                "Usuario: " + usuario + "\n" +
                "Rol: " + rol + "\n\n" +
                "Ya puedes iniciar sesión", 
                "Registro exitoso", 
                JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                this, 
                "No se pudo crear la cuenta.\n" +
                "El usuario podría ya existir.", 
                "Error de registro", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIniciarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSActionPerformed
        // Crear un panel personalizado para el login
    JPanel panel = new JPanel(new GridLayout(2, 2, 10, 10));
    JTextField txtUsuario = new JTextField(15);
    JPasswordField txtPassword = new JPasswordField(15);
    
    panel.add(new JLabel("Usuario:"));
    panel.add(txtUsuario);
    panel.add(new JLabel("Contraseña:"));
    panel.add(txtPassword);
    
    int resultado = JOptionPane.showConfirmDialog(
        this, 
        panel, 
        "Iniciar Sesión - SIBAL", 
        JOptionPane.OK_CANCEL_OPTION, 
        JOptionPane.PLAIN_MESSAGE
    );
    
    if (resultado == JOptionPane.OK_OPTION) {
        String usuario = txtUsuario.getText().trim();
        String password = new String(txtPassword.getPassword());
        
        // Validar que no estén vacíos
        if (usuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(
                this, 
                "Por favor completa todos los campos", 
                "Campos vacíos", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        // Validar credenciales
        ValidarAcceso validador = new ValidarAcceso();
        Usuario user = validador.iniciarSesion(usuario, password);
        
        if (user != null) {
            // Guardar sesión
            Sesion.getInstancia().iniciarSesion(user);
            
            JOptionPane.showMessageDialog(
                this, 
                "¡Bienvenido " + user.getNombre() + "!\nRol: " + user.getRol(), 
                "Inicio exitoso", 
                JOptionPane.INFORMATION_MESSAGE
            );
            
            // Abrir ventana principal (ajusta el nombre según tu formulario)
            new frmPrincipal().setVisible(true);
            this.dispose();  // Cerrar ventana de inicio
            
        } else {
            JOptionPane.showMessageDialog(
                this, 
                "Usuario o contraseña incorrectos.\nVerifica tus credenciales.", 
                "Error de acceso", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
        
        
    }//GEN-LAST:event_btnIniciarSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarS;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblFondoI;
    // End of variables declaration//GEN-END:variables
}
